CREATE DATABASE PARKX;

USE PARKX;

CREATE TABLE USERS(
    USER_ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100),
    EMAIL VARCHAR(100),
    PHONE VARCHAR(15)
);

CREATE TABLE PARKING_SLOTS(
    SLOT_ID INT PRIMARY KEY AUTO_INCREMENT,
    SLOT_NUMBER VARCHAR(10),
    STATUS VARCHAR(20)
);

CREATE TABLE BOOKINGS(
    BOOKING_ID INT PRIMARY KEY AUTO_INCREMENT,
    USER_ID INT,
    SLOT_ID INT,
    BOOKING_DATE DATE,
    FOREIGN KEY(USER_ID) REFERENCES USERS(USER_ID),
    FOREIGN KEY(SLOT_ID) REFERENCES PARKING_SLOTS(SLOT_ID)
);

INSERT INTO PARKING_SLOTS(SLOT_NUMBER, STATUS)
VALUES
('A1','Available'),
('A2','Booked'),
('A3','Available'),
('B1','Available'),
('B2','Booked');

SELECT * FROM PARKING_SLOTS;
